-- GABRIEL ALBINO - 3 SEMESTRE DE TSI 2025
USE EMPRESA;
-- 3.
-- A
INSERT INTO FUNCIONARIO(CPF, NOME, SALARIO, DATANASC, RUA, NUMERO, COMPL, BAIRRO, CIDADE, ESTADO, DNUMERO, SEXO)
VALUES ('999', 'Roberto Santos', 4500, '1972-06-21', 'Rua Benjamin', 34, NULL, 'Vila Maria', 'Santo André', 'SP', 1, 'M');
-- B
INSERT INTO DEPARTAMENTO (DNUMERO, DNOME) -- JÁ EXISTE UM DEPARTAMENTE COM ESSE DNUMERO
VALUES (1, 'Producao');
-- C
INSERT INTO DEPARTAMENTO (DNUMERO, DNOME, CPFGERENTE)
VALUES (10, 'Producao', '999');
-- D
DELETE FROM FUNCIONARIO WHERE CPF = '999'; -- NÃO PODE DELETAR O FUNCIONARIO QUE ESTÁ INSERIDO EM UMA OUTRA TABELA/DEPARTAMENTO (RELAÇÃO DE CHAVES)
-- E
UPDATE FUNCIONARIO SET DNUMERO = 20 WHERE CPF = '999'; -- O DEPARTAMENTO COM DNUMERO 20 NÃO EXISTE

-- 4.
INSERT INTO DEPARTAMENTO (DNUMERO, DNOME)
VALUES (2,'Ensino');

-- 5.
INSERT INTO DEPARTAMENTO (DNUMERO, DNOME)
VALUES (3,'RH');

-- 6.
UPDATE FUNCIONARIO SET DNUMERO = 2 WHERE CPF = '1234';

-- 7.
UPDATE FUNCIONARIO SET DNUMERO = 3 WHERE CPF = '6668';

-- 8. 
INSERT INTO ATRIBUICAO(CPF, PROJNUMERO)
VALUES ('1234', 5), ('9998', 5), ('9879', 5);

-- 9.
UPDATE FUNCIONARIO SET SALARIO = SALARIO*1.1 WHERE CPF IN (SELECT CPF FROM ATRIBUICAO WHERE PROJNUMERO = 4);

-- 10. 
INSERT INTO DEPARTAMENTO
VALUES (6, 'Marketing', '6668');

INSERT INTO PROJETO(PROJNOME, PROJLOCAL, DNUMERO)
VALUES ("Call-Center", "São Paulo", 6);

INSERT INTO ATRIBUICAO(CPF, PROJNUMERO)
VALUES ('1234', 7), ('3334', 7), ('4534', 7), ('6668', 7), ('8886', 7);

SELECT * FROM ATRIBUICAO WHERE PROJNUMERO = 7;
SELECT * FROM PROJETO WHERE PROJNUMERO = 7;

-- SELECT * FROM DEPARTAMENTO;
-- SELECT * FROM FUNCIONARIO;
-- SELECT * FROM ATRIBUICAO;
-- SELECT * FROM PROJETO;